export const siteConfig = {
  name: "Phrzy Snippet",
  shortName: "Phrzy",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://phrzy.eu.cc",
  description: "Simple snippet sharing for developers.",
  tagline: "Your code. Your snippets. One place.",
  subTagline: "Save, organize, and share your code snippets instantly.",
  github: "https://github.com/phrzy",
  languages: [
    "javascript",
    "typescript",
    "python",
    "html",
    "css",
    "json",
    "php",
    "java",
    "cpp",
    "bash",
    "go",
    "rust",
    "ruby",
    "sql",
    "yaml",
    "markdown",
  ],
  snippetsPerPage: 12,
  maxSnippetSize: 100000,
  maxTitleLength: 100,
  maxDescriptionLength: 500,
  maxTags: 10,
  maxTagLength: 30,
};
